"""rename address

Revision ID: 045471a20b5c
Revises: b0d97311d528
Create Date: 2025-12-28 11:01:34.439935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045471a20b5c'
down_revision = 'b0d97311d528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
